"""
scripts/probe_albert.py
-----------------------
Run before anything else. Checks:
  (a) lists models
  (b) tests chat
  (c) tests tools=[...] native support
  (d) tests /rerank endpoint
  (e) tests embeddings — reports dimension

Saves results to docs/albert_capabilities.md
This file is read by agent.py to decide whether to use native tools or ReAct fallback.
"""

import json
from pathlib import Path
from dotenv import load_dotenv
load_dotenv()

import esg_rag.albert as a

Path("docs").mkdir(exist_ok=True)
rows: list[str] = []

def check(label: str, fn):
    try:
        result = fn()
        msg = f"✅  {label}: {result}"
        rows.append(msg); print(msg)
        return result
    except Exception as e:
        msg = f"❌  {label}: {type(e).__name__}: {e}"
        rows.append(msg); print(msg)
        return None

print("\n── Albert API Probe ──\n")

# (a) List models
models = check("list_models", lambda: a.list_models()[:6])

# (b) Chat basic
check("chat_basic", lambda: (
    a.chat([{"role": "user", "content": "Reply with the single word OK"}])
    ["choices"][0]["message"]["content"][:20]
))

# (c) Native tool calls
def _test_tools():
    tools = [{
        "type": "function",
        "function": {
            "name": "get_scope1",
            "description": "Get Scope 1 emissions",
            "parameters": {
                "type": "object",
                "properties": {"company": {"type": "string"}},
                "required": ["company"],
            },
        }
    }]
    resp = a.chat(
        [{"role": "user", "content": "Get Scope 1 emissions for TotalEnergies"}],
        tools=tools,
    )
    msg = resp["choices"][0]["message"]
    if msg.get("tool_calls"):
        return f"native_tools=YES  call={msg['tool_calls'][0]['function']['name']}"
    return f"native_tools=NO  (model returned text, not tool call)"
check("chat_tools", _test_tools)

# (d) Rerank
def _test_rerank():
    docs = [
        "Paris weather is nice today.",
        "TotalEnergies reported Scope 1 GHG emissions of 35 Mt CO2e in 2024.",
        "Scope 3 upstream emissions represent 85% of the carbon footprint.",
    ]
    ranked = a.rerank("What are TotalEnergies Scope 1 emissions?", docs, top_n=3)
    return f"/rerank=OK  top_score={ranked[0]['score']:.3f}  top_idx={ranked[0]['index']}"
check("rerank", _test_rerank)

# (e) Embeddings — report dimension
def _test_embed():
    vecs = a.embed_texts(["TotalEnergies Scope 1 emissions 2024"])
    return f"embed_dim={len(vecs[0])}  n={len(vecs)}"
check("embeddings", _test_embed)

# Save report
report = (
    "# Albert API Capabilities\n\n"
    "Generated by scripts/probe_albert.py. "
    "Read by agent.py to decide tool-call strategy.\n\n"
    + "\n".join(rows) + "\n"
)
Path("docs/albert_capabilities.md").write_text(report)
print("\nSaved → docs/albert_capabilities.md")
print(report)
